version: '2'

services:
  simple_api:
    image: gsibble/simple_api:0.1 
    ports:
      - "8000:8000"
    links:
      - mysql
    depends_on:
      - "mysql"

  mysql:
    image: mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=hello
